# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Grax Media

# Short description (goes below the title; it will also be used in the RSS feed)
description: Continuous Improvement for your Life, your Team, and your Code

# Your name, as you want it to appear underneath each post and in the footer
author: David Walker

# Your email if you want it to be linked on the contact page
author_email:

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://coding-gt.grax.com

#### Under the Hood Stuff #####

permalink: none

# How many articles do you wish to appear on the front page:
paginate: 8

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, _site]

gems: [jekyll-sitemap]

collections:
  tags:
    output: true
    permalink: /improve/your/:path/
    
  home_page_sections:
    output: false
  
  page_sections:
    output: false
  
  authors:
    output: false
    
defaults:
  -
    scope:
        path: blank
        type: home_page_sections
    values:
        layout: ""
  -
    scope:
        path: ""
        type: tags
    values:
        layout: category
 
